import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Banner from '../components/Banner'


export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon | From A to Z</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/amazon_icon.ico" />
      </Head>
      
      <Header />
      
      <main className='mx-auto w-full'>
        <Banner />
      </main>      
    </div>
  )
}
