import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon | From A to Z</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/amazon_icon.ico" />
      </Head>
      <Header />      
    </>
  )
}
